version: '3.5'

services:
    # Frontend
    web:
        build:
            context: ./web
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
        networks:
            meet.jitsi:
        depends_on:
            - jvb
        
    # XMPP server
    prosody:
        build:
            context: ./prosody
        expose:
            - '${XMPP_PORT:-5222}'
            - '${PROSODY_S2S_PORT:-5269}'
            - '5347'
            - '${PROSODY_HTTP_PORT:-5280}'
        networks:
            meet.example.org:
    # Focus component
    jicofo:
        build:
            context: ./jicofo
        ports:
            - '127.0.0.1:${JICOFO_REST_PORT:-8888}:8888'
        depends_on:
            - prosody
        networks:
            meet.example.org:
    # Video bridge
    jvb:
        build:
            context: ./jvb
        ports:
            - '${JVB_PORT:-10000}:${JVB_PORT:-10000}/udp'
            - '127.0.0.1:${JVB_COLIBRI_PORT:-8080}:8080'
        depends_on:
            - prosody
        networks:
            meet.example.org:
# Custom network so all services can communicate using a FQDN
networks:
    meet.example.org:
